version: '3.8'

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/docker_data/obsidian/config:/config
      - ~/docker_data/obsidian/vaults:/vaults
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri # optional
    shm_size: "1gb"
    restart: unless-stopped
